language: android
jdk: oraclejdk8
dist: trusty
sudo: required

group: edge

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - android-sdk-license-.+

notifications:
  email: false

before_install:
  - bash .android-license.sh

  - pip install --user codecov
  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

branches:
  only:
    - feature/ci-cd
    - develop

before_script:
  - chmod +x gradlew
  - ./gradlew clean

script:
  - ./gradlew assembleDebug
  - ./gradlew testDebugUnitTest
  - echo no | $ANDROID_SDK_HOME/tools/bin/avdmanager create avd -n beast --force -c 2048M -k 'system-images;android-28;google_apis;x86'
  - emulator -avd beast -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedDebugAndroidTest

after_success:
  # - codecov